### ISSUE TITLE
missing iproute2 build dockerfile

### ISSUE THREAD

**Issue by llhhbc** [cilium/image-tools#230]
I want build cilium 1.12.7 image by myself, but I can't found iproute2 dockerfile.

**Comment by lizrice** [comment]
This probably deserves a little more context to explain the move: iproute2 includes some GPL-licensed code that isn't compatible with the CNCF licensing policy. Since we're not using it in recent versions of Cilium any more it made sense to remove the repo from the Cilium project, but we made it available under the Isovalent org so that people can still get to it if necessary (as in this case)

**Comment by llhhbc** [comment]
OK, thanks. May I ask which version you started to remove the dependency on iproute? Will you no longer use tc in the future? What should I replace it with?

**Comment by gandro** [comment]
> OK, thanks. May I ask which version you started to remove the dependency on iproute? Will you no longer use tc in the future? What should I replace it with?

The iproute2 fork was removed in this PR: https://github.com/cilium/cilium/pull/26221 - `iproute2` is still shipped as part of the Cilium image, but we're now using the upstream version.
We now use the `github.com/cilium/ebpf` library to load BPF programs: https://github.com/cilium/cilium/pull/24876  

Those changes are present in the branches of v1.14 and newer

**Comment by llhhbc** [comment]
Thanks very much.
